### ISSUE TITLE
Auth problem

### ISSUE THREAD

**Issue by ronek22** [dnstanciu/drf-angular-docker-tutorial#2]
Hi,
I have small problem with authentication. After login everything works well, but when I refresh page I lose auth state and I need to login again.

Do you have any idea to fix this issue?

**Comment by dnstanciu** [comment]
Not sure I have enough info to help. Have you solved this in the mean time? Can you check logs?

**Comment by ronek22** [comment]
Yes, I solved this. As far as I can remember, I used localStorage to store authentication data. Maybe it's not super safety, but at least it works

**Comment by dnstanciu** [comment]
Ok, thanks for the update.
